### ISSUE TITLE
i clicked "Instructions"... and what do you know? a crash!

### ISSUE THREAD

**Issue by NyanMC** [CoffeeCatRailway/BubbleBurst#1]
Here's the crash report
https://www.dropbox.com/s/86fjc13khvnbg7a/crash-2018-12-08_09.54.53-client.txt?dl=0

**Comment by ELJOKER900** [comment]
yeah this happened me

**Comment by NyanMC** [comment]
my brother in christ this is a nearly five year old issue

**Comment by ELJOKER900** [comment]
bruh
